import Hosts from 'Assemblies/Common/Constants/Roblox.Common.Constants/Hosts';
import { DYNAMIC_LOGVARIABLE, FASTFLAGVARIABLE, LOGVARIABLE, SYNCHRONIZED_LOGGROUP, SYNCHRONIZED_LOGVARIABLE } from './FastLog';

export class FastLogGlobal {
	public static Init() {
		LOGVARIABLE('GumePersistince', 0);
		LOGVARIABLE('TheInternalSystem', 0);
		LOGVARIABLE('AandBTusting', 0);
		LOGVARIABLE('SIMPLEPING', 0);
		LOGVARIABLE('Protocol77', 0);
		LOGVARIABLE('DataStoreV2', 7);
		LOGVARIABLE('DataStore', 7);
		LOGVARIABLE('EphemeralCountersV2', 7);
		LOGVARIABLE('EphemeralCounters', 7);
		LOGVARIABLE('Stats', 7);
		LOGVARIABLE('Grid', 7);
		LOGVARIABLE('dmp', 7);
		LOGVARIABLE('CsrfAPIV1', 7);
		LOGVARIABLE('ClientSettingsAPIV1', 7);
		LOGVARIABLE('WWWAuthV1', 7);
		LOGVARIABLE('ClientTelementry', 7);
		DYNAMIC_LOGVARIABLE('Tasks', 7);
		SYNCHRONIZED_LOGVARIABLE(Hosts['Apex'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['WebHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['ApiProxyHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['StaticCDN'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['JavaScriptCDN'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['CSSCDN'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['ImagesCDN'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['SetupCDN'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['EphemeralCountersService'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['EphemeralCountersV2'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['TemporaryImagesCDN'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['VersionCompatibilityService'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['ClientSettingsService'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['AssetGameHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['GamePersistenceHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['MarketplaceService'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['MetricsHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['ApiGatewayHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['ApiGatewayCDNHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['DEPRECATED_CaptchaHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['AuthenticationHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['LocaleHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['AbTestingHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['UsersHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['TSVHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['LatencyMeasurementsHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['ChatHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['ContactsHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['NotificationsHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['AccountSettingsHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['AdsHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['TradesHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['FriendsHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['PrivateMessagesHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['EconomyHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['GamesHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['RealTimeHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['ThumbsHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['PresenceHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['GroupsHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['AccountInformationHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['BadgesHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['DeveloperForumHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['PremiumFeaturesHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['ClientSettingsHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['ClientSettingsCDNHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['AdConfigurationHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['ClientTelementryServiceHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['AssetsHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['AvatarHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['BillingHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['CatalogHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['CdnProvidersHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['ChatModerationHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['ContentStoreHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['DevelopHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['DiscussionsHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['EconomyCreatorStatsHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['EngagementPayoutsHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['FollowingsHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['G18NHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['GameJoinHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['GroupsModerationHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['InventoryHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['ItemConfigurationHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['LocalizationTablesHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['PointsHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['PublishHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['PunishmentsService'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['ShareHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['TextFilterHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['ThemesHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['ThumbnailsResizerHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['TranslationRolesHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['TranslationsHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['UserModerationHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['VoiceHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['FilesService'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['MetricsInternalWebsiteHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['AbTestingService'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['AdminWebsiteHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['CSWebsiteHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['ComApisCDNHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['PointsServiceHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['UsersServiceHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['DataHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['MidasHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['DEPRECATED_ApiGatewayRCSHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['NomadHost'], 0);
		SYNCHRONIZED_LOGVARIABLE(Hosts['CSRHost'], 0);

		FASTFLAGVARIABLE('RequireGlobalHTTPS', true);
	}

	public static IncludeHostLogLevels() {
		SYNCHRONIZED_LOGGROUP(Hosts['Apex']);
		SYNCHRONIZED_LOGGROUP(Hosts['WebHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['ApiProxyHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['StaticCDN']);
		SYNCHRONIZED_LOGGROUP(Hosts['JavaScriptCDN']);
		SYNCHRONIZED_LOGGROUP(Hosts['CSSCDN']);
		SYNCHRONIZED_LOGGROUP(Hosts['ImagesCDN']);
		SYNCHRONIZED_LOGGROUP(Hosts['SetupCDN']);
		SYNCHRONIZED_LOGGROUP(Hosts['EphemeralCountersService']);
		SYNCHRONIZED_LOGGROUP(Hosts['EphemeralCountersV2']);
		SYNCHRONIZED_LOGGROUP(Hosts['TemporaryImagesCDN']);
		SYNCHRONIZED_LOGGROUP(Hosts['VersionCompatibilityService']);
		SYNCHRONIZED_LOGGROUP(Hosts['ClientSettingsService']);
		SYNCHRONIZED_LOGGROUP(Hosts['AssetGameHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['GamePersistenceHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['MarketplaceService']);
		SYNCHRONIZED_LOGGROUP(Hosts['MetricsHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['ApiGatewayHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['ApiGatewayCDNHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['DEPRECATED_CaptchaHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['AuthenticationHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['LocaleHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['AbTestingHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['UsersHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['TSVHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['LatencyMeasurementsHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['ChatHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['ContactsHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['NotificationsHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['AccountSettingsHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['AdsHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['TradesHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['FriendsHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['PrivateMessagesHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['EconomyHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['GamesHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['RealTimeHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['ThumbsHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['PresenceHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['GroupsHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['AccountInformationHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['BadgesHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['DeveloperForumHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['PremiumFeaturesHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['ClientSettingsHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['ClientSettingsCDNHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['AdConfigurationHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['ClientTelementryServiceHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['AssetsHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['AvatarHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['BillingHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['CatalogHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['CdnProvidersHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['ChatModerationHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['ContentStoreHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['DevelopHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['DiscussionsHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['EconomyCreatorStatsHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['EngagementPayoutsHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['FollowingsHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['G18NHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['GameJoinHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['GroupsModerationHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['InventoryHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['ItemConfigurationHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['LocalizationTablesHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['PointsHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['PublishHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['PunishmentsService']);
		SYNCHRONIZED_LOGGROUP(Hosts['ShareHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['TextFilterHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['ThemesHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['ThumbnailsResizerHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['TranslationRolesHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['TranslationsHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['UserModerationHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['VoiceHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['FilesService']);
		SYNCHRONIZED_LOGGROUP(Hosts['MetricsInternalWebsiteHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['AbTestingService']);
		SYNCHRONIZED_LOGGROUP(Hosts['AdminWebsiteHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['CSWebsiteHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['ComApisCDNHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['PointsServiceHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['UsersServiceHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['DataHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['MidasHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['DEPRECATED_ApiGatewayRCSHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['NomadHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['CSRHost']);
	}
}
